SELECT 
A.artist,
ROUND(CAST((SELECT COUNT(RATING) FROM ALBUM WHERE RATING < 3 AND artist = A.artist) AS NUMERIC)/
CAST((SELECT COUNT(TITLE) FROM ALBUM WHERE artist = A.artist) AS NUMERIC) * 100.00, 2)
FROM ALBUM AS A
GROUP BY (A.artist)
ORDER BY CAST((SELECT COUNT(RATING) FROM ALBUM WHERE RATING < 3 AND artist = A.artist) AS NUMERIC)/
	 CAST((SELECT COUNT(TITLE) FROM ALBUM WHERE artist = A.artist) AS NUMERIC)