SELECT DISTINCT A.artist FROM ALBUM AS A
WHERE (SELECT COUNT(type) FROM ALBUM
	WHERE ARTIST = A.artist AND type != 'STUDIO') > 
	(SELECT COUNT(type) FROM ALBUM
	WHERE ARTIST = A.artist AND type = 'STUDIO')